# Standards: 0.11
---

# 2.1.15 Ensure mail transfer agent is configured for local-only mode
- name: 2.1.15 - Check if postfix configure file exist
  stat:
    path: "{{ cis_postfix_configure_filename }}"
  register: postfix_configure_2_1_15
  tags:
    - level-1
    - "2.1.15"
    - scored

- name: 2.1.15 - Ensure loopback only is configured for postfix
  copy:
    dest: "{{ cis_postfix_configure_filename }}"
    content: "inet_interfaces = loopback-only\n"
  when: postfix_configure_2_1_15.stat.exists is not defined or not postfix_configure_2_1_15.stat.exists
  tags:
    - level-1
    - "2.1.15"
    - scored

- name: 2.1.15 - Ensure chrony is configure
  lineinfile:
    dest: "{{ cis_postfix_configure_filename }}"
    regexp: "^inet_interfaces\\s+"
    line: "inet_interfaces = loopback-only"
  when: postfix_configure_2_1_15.stat.exists is defined or postfix_configure_2_1_15.stat.exists
  tags:
    - level-1
    - "2.1.15"
    - scored

- name: 2.1.15 Ensure mail transfer agent is configured for local-only mode
  systemd:
    name: "snmpd"
    enabled: yes
    state: restarted
  ignore_errors: True
  tags:
    - level-1
    - "2.1.15"
    - scored