# Standards: 0.11
---

# 3.2.3 Ensure secure ICMP redirects are not accepted 

- name: 3.2.3 - Ensure secure ICMP redirects are not accepted 
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.3"
    - scored

- name: 3.2.3 - Ensure secure ICMP redirects are not accepted
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.3"
    - scored

- name: 3.2.3 - Ensure secure ICMP redirects are not accepted in active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.conf.all.secure_redirects=0"
    - "sysctl -w net.ipv4.conf.default.secure_redirects=0"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.2.3"
    - scored
