# Standards: 0.11
---

# 3.2.4 Ensure suspicious packets are logged 

- name: 3.2.4 - Ensure suspicious packets are logged 
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.4"
    - scored

- name: 3.2.4 - Ensure suspicious packets are logged
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: 1
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.4"
    - scored

- name: 3.2.4 - Ensure suspicious packets are logged in active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.conf.all.log_martians=1"
    - "sysctl -w net.ipv4.conf.default.log_martians=1"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.2.4"
    - scored
