# Standards: 0.11
---

# 5.2.15 Ensure that strong Key Exchange algorithms are used 

- name: 5.2.15 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_15
  tags:
    - level-1
    - section-5
    - "5.2.15"
    - scored

- name: 5.2.15 - Ensure that strong Key Exchange algorithms are used 
  lineinfile:
    regexp: "^KexAlgorithms\\s+"
    line: "KexAlgorithms {{ cis_sshd_kexalgorithms }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_15.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.15"
    - scored